Corrected TF file
yandex-cloud-examples/yc-data-proc-configure-network pull request #4
Opened 2024-11-29 13:42 UTC by mikhaildoc-documentat

2024-12-28 04:55 UTC, Odyvia42 requested changes

2024-12-28 04:55 UTC, Odyvia42 commented on data-proc-nat-gateway.tf
> +        "${file(local.path_to_ssh_public_key)}"
Погоди, тут же было правильно. Мы наоборот, приводим всё к виду:
```
ssh_public_keys = [
  file("<путь_к_открытому_SSH-ключу>")
]
```

Давай вернём как было.

2024-12-28 08:57 UTC, mikhaildoc-documentat commented on data-proc-nat-gateway.tf
> +        "${file(local.path_to_ssh_public_key)}"
Тут используется локальная переменная, с ней нужно записывать именно так

2025-01-10 05:21 UTC, Odyvia42 commented on data-proc-nat-gateway.tf
> +        "${file(local.path_to_ssh_public_key)}"
Окей, теперь понял. Спасибо, что объяснил.

2025-01-10 05:23 UTC, Odyvia42 approved these changes

2025-01-10 14:03 UTC, lanieuszko approved these changes

2025-01-10 14:06 UTC, merged